version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 484726675287.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - docker build -t conference-backend .
      - docker tag conference-backend:latest 484726675287.dkr.ecr.eu-central-1.amazonaws.com/conference-backend:latest
      - docker push 484726675287.dkr.ecr.eu-central-1.amazonaws.com/conference-backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/conference-0.0.1-SNAPSHOT.jar
