spring:
  datasource:
    platform: postgres
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:30432/postgres}
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 10000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    show-sql: true

#server:
#  port: 9093